//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMARK
{
    using System;
    using System.Collections.Generic;
    
    public partial class peliculasTable
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string director { get; set; }
        public string genero { get; set; }
        public int rating { get; set; }
        public string imagen { get; set; }
    }
}
